language: node_js
node_js:
  - "10"

cache: yarn

addons:
  chrome: stable

# Define environment variables
env:
  - secure: "GOdoNQ+r7dn1A1UXznym68WkLH57GBWJ4zN4/gOdAcrUWMJaQJCGmDrqo9v9uk2nj3Mz05NV5GvwEsWz3lWzeA1kzmKY6k7vqS+wZOTMBch0iboa12nT2DBALb5TwGi10whfBIAk/NDCfpJeQ01q88Cl7yV3vBoynlzMUiAw/N8Z0meEjdcAQRuD10lKfos7fJd9WCr6LvRJb9rm0Zq0MAqNLw6ZBA2aVz8Jfz4QrBB6oZJwMu0T/URJoX96kQ6WFPDevPCLjT1V2ezCOWyyTYHdUf6C7Omod9TvWSthTGXs0Wr/epY6e51R+e4tMVr/+dA41jetwmvfFTf0HuefQ1+v5EuQj/UD6vsidxf3wohesnfxzJastuA0wcYm8zK99lQlXhqRB2YB9r+sZII339my3icRBImsX2oj7Vu+tzDMx0092ifQLktHwmX5VrVKdg8iACzq7CA11vKLDUp6ickXiDGxymVEbPRa6SIZWoX0pRQcAHrPNwDHpa0u005/zVinZHACAdLxq4hYMfhwJQ92Uq22+Yv2eAwgqieJJaMUyfJeb5AL3wKSyKufLYvMUuX8wbTg1hdzFMhtYfbM+m6qTosgWjm5aAr5Jqqk0dV9j+GjArUTDYnzGeTxespNyBebfE1+LvoMS6WmR0qt2FMM5B93X2t3+Rdn7nVenGo="

git:
  depth: false

install:
  - yarn global add @angular/cli
  - yarn install
  - ./get-info.sh

jobs:
    include:
        - stage: test
          script: yarn run lint && yarn run test
          fast_finish: true
        - stage: deploy
          if: branch = develop AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh testing
        - stage: deploy
          if: branch =~ /^release\/.*$/ AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh stage
        - stage: deploy
          if: (NOT branch = master) AND tag IS present
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh develop
        - stage: deploy
          if: branch = master AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh front && ./build-deploy.sh demo
